### ISSUE TITLE
Implement the presentation/GUI

### ISSUE THREAD

**Issue by DavidPrichard** [4102/Sentimental-Stats#1]

**Comment by yvadalia** [comment]
Noah, any updates on presentation layer?

**Comment by noah-potter** [comment]
Still working on it. Other projects were getting in the way

Date: Mon, 18 Apr 2016 11:41:47 -0700

**Comment by yvadalia** [comment]
Thats okay! we will try to complete all the modules and integrate them all by tomorrow morning

**Comment by noah-potter** [comment]
Oh actually i just saw someone implemented scala-chart. That looks good to be, my stuff was starting to get overly complex and would require too many structural changes. Can we just continue using scala-chart and mark this as done?

**Comment by DavidPrichard** [comment]
That was me. The function that makes the actual chart, "graph", is just producing test data right now. It needs to be set put to actually do something with the data from the Team instances it is passed, rather than just using their names.

**Comment by noah-potter** [comment]
Oh gotcha
